apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-deployment
  labels:
    name: env-test
spec:
  replicas: 4
  selector:
    matchLabels:
      name: env-test
  template:
    metadata:
      labels:
        name: env-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.17
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 10
